### PR TITLE
Move Tambo arg parser source out of ice.py

### PR DESCRIPTION
**Pull request by trhoden**
When ice_setup was a monolithic script, everything needed
to be in one file.  Now that it is a module, start to move things
into more manageably sized files.

Start by moving the in-lined Tambo parser back out into it's original
source structure, modifying it slightly for clarity.

Signed-off-by: Travis Rhoden <trhoden@redhat.com>

### CODE REVIEW

**Comment by alfredodeza** [comment]
aren't we supposed to make this an actual requirement? `tambo` is released on PyPI with a permissive license

**Comment by trhoden** [comment]
Hmm, I was just doing this because I felt like it...  :)  I didn't think we could have any package dependencies whatsoever?  if I can have tambo from pypi, why not argparse for PY 2.6?

**Comment by alfredodeza** [comment]
you can now that it is a package! Before this was a no-go because the requirement was to be a single file in a tarball :)

**Comment by trhoden** [comment]
seriously?  ugh.  :)  I thought it was more about working without external network access.

**Comment by ktdreyer** [comment]
As much as I'd love to see tambo split out into its own package, I think it's going to need to go into "ice_setup 2.0" or something.

From the Red Hat Ceph product perspective, I thought we were going to simply have users run "`yum localinstall path/to/ice_setup.rpm`" to get ice_setup installed so we can continue on with setting up the offline repository. If we add more packages onto that command, like `yum localinstall path/to/ice_setup.rpm path/to/python-tambo.rpm`, it's going to get a bit unweildy :/

**Comment by alfredodeza** [comment]
Since the move is clearly something imminent, I would suggest to the module move in a way that preserves the actual structure of the `tambo` package (https://github.com/alfredodeza/tambo/tree/master/tambo) so that when there is a move the change can be done in similar fashion as we do in `ceph-deploy` https://github.com/ceph/ceph-deploy/blob/master/ceph_deploy/lib/__init__.py#L22-27

**Comment by ktdreyer** [comment]
@alfredodeza sure, that would work for me.

**Comment by trhoden** [comment]
I'm happy to table this for now, as it's not important for moving forward.  I had just thought it was an easy way to move the Tambo code out of ice.py, mostly for aesthetics.

I did actually try preserving the tambo source structure by adding at as a git subtree and using a symlink.  This works, except that the Tambo imports then fail, which is what Alfredo is referring to at https://github.com/ceph/ceph-deploy/blob/master/ceph_deploy/lib/__init__.py#L3.

Since we don't really know the long-term plans here, it seems like more effort than needed to introduce the whole vendoring concept to ice-setup.  What do you think?

**Comment by alfredodeza** [comment]
@trhoden agreed!

**Comment by trhoden** [comment]
Thanks.  I'll just close this for now.  To be revisited (or not!) in the future.

**Pull request closed without merging**
